export const categories = [
    {name:'Electronics',
    sub:[
        'Televisions',
'Home Appliances',
'Home Theater & Audio',
'Cell Phones',
'Digital Cameras',
'Tablets',
'Headphones',
'Digital Cameras',
'Maker',
'Portable Speakers',
'Pro Audio & Musical Instruments'
]
    },
    {name:'Toys',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'Foods',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'Closes',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'Skin & Care',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'Special Nutrition',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'Sport & Outdoor',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'Books',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
    {name:'toys',
    sub:[
        'Action Figures & Statue',
  'Arts & Crafts',
  'Baby & Toddler Toys',
  'Building Toys',
  'Dolls & Accessories',
  'Dress Up & Pretend Play',
  "Kids' Electronics",
  'Games',
  'Grown-Up Toys',
  'Hobbies',
  "Kids' Furniture",
  ' Décor & Storage',
  'Learning & Education',
  'Novelty & Gag Toys',
  'Party Supplies',
  'Puppets',
  'Puzzles',
  'Sports & Outdoor Play',
  'Stuffed Animals & Plush Toys',
  'Toy Remote Control & Play Vehicles',
  'Tricycles',
  ' Scooters & Wagons',
  'Video Games'
]
    },
]