export const categories = [
    {name:'Electronics',
    sub:[
        {id:0,
        name:'Computers'},
        {id:1,
        name:'Phones'},
        {id:2,
        name:'Tablets'},
        {id:3,
        name:'Tv'},
]
    },
    {name:'Foods',
    sub:[
        {id:0,
        name:'Alcohol'},
        {id:1,
        name:'Fruits'},
        {id:2,
        name:'Candies'},
        {id:3,
        name:'Coffee'},
]
    },
    
    {name:'Clothes',
    sub:[
        {id:0,
        name:'Women'},
        {id:1,
        name:'Man'},
        {id:2,
        name:'Kid'},
        
]
    },
    {name:'Skin & Care',
    sub:[
        {id:0,
        name:'Face'},
        {id:1,
        name:'Hair'},
        {id:2,
        name:'Perfumes'},
        {id:3,
        name:'Covid'},
]
    },
    {name:'Special Nutrition',
    sub:[
        {id:0,
        name:'Diabetes'},
        {id:1,
        name:'Babies'},
        {id:2,
        name:'Sport'},
        
]
    },
    {name:'Sport & Outdoor',
    sub:[
        {id:0,
        name:'Suits'},
        {id:1,
        name:'Footwear'},
        {id:2,
        name:'Fitness'},
        {id:3,
        name:'Swimming'},
]
    },
    {name:'Books',
    sub:[
        {id:0,
        name:''},
        {id:1,
        name:'Educational'},
        {id:2,
        name:'Adventures'},
        {id:3,
        name:'Historical'},
]
    },
    {name:'Toys',
    sub:[
        {id:0,
        name:'Cars'},
        {id:1,
        name:'Dols'},
        {id:2,
        name:'Guns'},
        
]
    },
]